### PR TITLE
Update .pre-commit-config.yaml

### PR DESCRIPTION
**Pull request by amanmdesai**

### CODE REVIEW

**Comment by amanmdesai** [comment]
@klieret I have been trying to resolve the issue, but it seems it blacken-docs cannot be added to pre-commit, no idea whats wrong. Could you please help?

**Comment by klieret** [comment]
Could this be an indentation issue?

**Comment by amanmdesai** [comment]
> Could this be an indentation issue?

yes, it was an indentation issue. I resolved it now. 

Will open a PR in our matplotlib repo

**Comment by amanmdesai** [comment]
Thanks @klieret

**Pull request closed without merging**
